LoRA_type:
  desc: null
  sort: 77
  value: Standard
LyCORIS_preset:
  desc: null
  sort: 123
  value: full
adaptive_noise_scale:
  desc: null
  sort: 74
  value: 0
additional_parameters:
  desc: null
  sort: 94
  value: ''
block_alphas:
  desc: null
  sort: 102
  value: ''
block_dims:
  desc: null
  sort: 101
  value: ''
block_lr_zero_threshold:
  desc: null
  sort: 100
  value: ''
bucket_no_upscale:
  desc: null
  sort: 62
  value: true
bucket_reso_steps:
  desc: null
  sort: 64
  value: 64
cache_latents:
  desc: null
  sort: 20
  value: true
cache_latents_to_disk:
  desc: null
  sort: 21
  value: false
caption_dropout_every_n_epochs:
  desc: null
  sort: 66
  value: 0.0
caption_dropout_rate:
  desc: null
  sort: 67
  value: 0
caption_extension:
  desc: null
  sort: 22
  value: ''
clip_skip:
  desc: null
  sort: 43
  value: '1'
color_aug:
  desc: null
  sort: 41
  value: false
constrain:
  desc: null
  sort: 83
  value: 0.0
conv_alpha:
  desc: null
  sort: 89
  value: 1
conv_block_alphas:
  desc: null
  sort: 104
  value: ''
conv_block_dims:
  desc: null
  sort: 103
  value: ''
conv_dim:
  desc: null
  sort: 88
  value: 1
debiased_estimation_loss:
  desc: null
  sort: 124
  value: false
decompose_both:
  desc: null
  sort: 86
  value: false
dim_from_weights:
  desc: null
  sort: 40
  value: false
down_lr_weight:
  desc: null
  sort: 97
  value: ''
enable_bucket:
  desc: null
  sort: 23
  value: true
epoch:
  desc: null
  sort: 14
  value: 1
factor:
  desc: null
  sort: 78
  value: -1
flip_aug:
  desc: null
  sort: 42
  value: false
fp8_base:
  desc: null
  sort: 25
  value: false
full_bf16:
  desc: null
  sort: 119
  value: false
full_fp16:
  desc: null
  sort: 26
  value: false
gpu_ids:
  desc: null
  sort: 47
  value: ''
gradient_accumulation_steps:
  desc: null
  sort: 48
  value: '1'
gradient_checkpointing:
  desc: null
  sort: 24
  value: false
headless:
  desc: null
  sort: 0
  value:
    label: 'False'
keep_tokens:
  desc: null
  sort: 58
  value: '0'
learning_rate:
  desc: null
  sort: 10
  value: 0.0001
logging_dir:
  desc: null
  sort: 6
  value: C:\Users\94427\kashiwa\Asuka\logs
lora_network_weights:
  desc: null
  sort: 39
  value: ''
lr_scheduler:
  desc: null
  sort: 11
  value: cosine
lr_scheduler_args:
  desc: null
  sort: 70
  value: ''
lr_scheduler_num_cycles:
  desc: null
  sort: 59
  value: ''
lr_scheduler_power:
  desc: null
  sort: 60
  value: ''
lr_warmup:
  desc: null
  sort: 12
  value: '10'
max_bucket_reso:
  desc: null
  sort: 29
  value: 2048
max_data_loader_n_workers:
  desc: null
  sort: 55
  value: '0'
max_grad_norm:
  desc: null
  sort: 71
  value: 1
max_resolution:
  desc: null
  sort: 9
  value: 512,512
max_timestep:
  desc: null
  sort: 121
  value: 1000
max_token_length:
  desc: null
  sort: 52
  value: '75'
max_train_epochs:
  desc: null
  sort: 53
  value: ''
max_train_steps:
  desc: null
  sort: 54
  value: ''
mem_eff_attn:
  desc: null
  sort: 49
  value: false
mid_lr_weight:
  desc: null
  sort: 98
  value: ''
min_bucket_reso:
  desc: null
  sort: 28
  value: 256
min_snr_gamma:
  desc: null
  sort: 96
  value: 0
min_timestep:
  desc: null
  sort: 120
  value: 0
mixed_precision:
  desc: null
  sort: 16
  value: fp16
model_list:
  desc: null
  sort: 51
  value: runwayml/stable-diffusion-v1-5
module_dropout:
  desc: null
  sort: 116
  value: 0
multi_gpu:
  desc: null
  sort: 46
  value: false
multires_noise_discount:
  desc: null
  sort: 76
  value: 0
multires_noise_iterations:
  desc: null
  sort: 75
  value: 0
network_alpha:
  desc: null
  sort: 56
  value: 1
network_dim:
  desc: null
  sort: 38
  value: 8
network_dropout:
  desc: null
  sort: 114
  value: 0
noise_offset:
  desc: null
  sort: 73
  value: 0
noise_offset_type:
  desc: null
  sort: 72
  value: Original
num_cpu_threads_per_process:
  desc: null
  sort: 19
  value: 2
num_machines:
  desc: null
  sort: 45
  value: 1
num_processes:
  desc: null
  sort: 44
  value: 1
optimizer:
  desc: null
  sort: 68
  value: AdamW8bit
optimizer_args:
  desc: null
  sort: 69
  value: ''
output_dir:
  desc: null
  sort: 8
  value: C:\Users\94427\kashiwa\Asuka\outputs9
output_name:
  desc: null
  sort: 50
  value: last
parameters:
  desc: null
  sort: 125
  value:
  - - headless
    - label: 'False'
  - - print_only
    - label: 'False'
  - - pretrained_model_name_or_path
    - runwayml/stable-diffusion-v1-5
  - - v2
    - false
  - - v_parameterization
    - false
  - - sdxl
    - false
  - - logging_dir
    - C:\Users\94427\kashiwa\Asuka\logs
  - - reg_data_dir
    - ''
  - - output_dir
    - C:\Users\94427\kashiwa\Asuka\outputs9
  - - max_resolution
    - 512,512
  - - learning_rate
    - 0.0001
  - - lr_scheduler
    - cosine
  - - lr_warmup
    - '10'
  - - train_batch_size
    - 1
  - - epoch
    - 1
  - - save_every_n_epochs
    - 1
  - - mixed_precision
    - fp16
  - - save_precision
    - fp16
  - - seed
    - ''
  - - num_cpu_threads_per_process
    - 2
  - - cache_latents
    - true
  - - cache_latents_to_disk
    - false
  - - caption_extension
    - ''
  - - enable_bucket
    - true
  - - gradient_checkpointing
    - false
  - - fp8_base
    - false
  - - full_fp16
    - false
  - - stop_text_encoder_training_pct
    - 0
  - - min_bucket_reso
    - 256
  - - max_bucket_reso
    - 2048
  - - xformers
    - xformers
  - - save_model_as
    - safetensors
  - - shuffle_caption
    - false
  - - save_state
    - false
  - - resume
    - ''
  - - prior_loss_weight
    - 1.0
  - - text_encoder_lr
    - 0.0001
  - - unet_lr
    - 0.0001
  - - network_dim
    - 8
  - - lora_network_weights
    - ''
  - - dim_from_weights
    - false
  - - color_aug
    - false
  - - flip_aug
    - false
  - - clip_skip
    - '1'
  - - num_processes
    - 1
  - - num_machines
    - 1
  - - multi_gpu
    - false
  - - gpu_ids
    - ''
  - - gradient_accumulation_steps
    - '1'
  - - mem_eff_attn
    - false
  - - output_name
    - last
  - - model_list
    - runwayml/stable-diffusion-v1-5
  - - max_token_length
    - '75'
  - - max_train_epochs
    - ''
  - - max_train_steps
    - ''
  - - max_data_loader_n_workers
    - '0'
  - - network_alpha
    - 1
  - - training_comment
    - ''
  - - keep_tokens
    - '0'
  - - lr_scheduler_num_cycles
    - ''
  - - lr_scheduler_power
    - ''
  - - persistent_data_loader_workers
    - false
  - - bucket_no_upscale
    - true
  - - random_crop
    - false
  - - bucket_reso_steps
    - 64
  - - v_pred_like_loss
    - 0
  - - caption_dropout_every_n_epochs
    - 0.0
  - - caption_dropout_rate
    - 0
  - - optimizer
    - AdamW8bit
  - - optimizer_args
    - ''
  - - lr_scheduler_args
    - ''
  - - max_grad_norm
    - 1
  - - noise_offset_type
    - Original
  - - noise_offset
    - 0
  - - adaptive_noise_scale
    - 0
  - - multires_noise_iterations
    - 0
  - - multires_noise_discount
    - 0
  - - LoRA_type
    - Standard
  - - factor
    - -1
  - - use_cp
    - false
  - - use_tucker
    - false
  - - use_scalar
    - false
  - - rank_dropout_scale
    - false
  - - constrain
    - 0.0
  - - rescaled
    - false
  - - train_norm
    - false
  - - decompose_both
    - false
  - - train_on_input
    - true
  - - conv_dim
    - 1
  - - conv_alpha
    - 1
  - - sample_every_n_steps
    - 0
  - - sample_every_n_epochs
    - 0
  - - sample_sampler
    - euler_a
  - - sample_prompts
    - ''
  - - additional_parameters
    - ''
  - - vae_batch_size
    - 0
  - - min_snr_gamma
    - 0
  - - down_lr_weight
    - ''
  - - mid_lr_weight
    - ''
  - - up_lr_weight
    - ''
  - - block_lr_zero_threshold
    - ''
  - - block_dims
    - ''
  - - block_alphas
    - ''
  - - conv_block_dims
    - ''
  - - conv_block_alphas
    - ''
  - - weighted_captions
    - false
  - - unit
    - 1
  - - save_every_n_steps
    - 0
  - - save_last_n_steps
    - 0
  - - save_last_n_steps_state
    - 0
  - - use_wandb
    - false
  - - wandb_api_key
    - ''
  - - scale_v_pred_loss_like_noise_pred
    - false
  - - scale_weight_norms
    - 0
  - - network_dropout
    - 0
  - - rank_dropout
    - 0
  - - module_dropout
    - 0
  - - sdxl_cache_text_encoder_outputs
    - false
  - - sdxl_no_half_vae
    - true
  - - full_bf16
    - false
  - - min_timestep
    - 0
  - - max_timestep
    - 1000
  - - vae
    - ''
  - - LyCORIS_preset
    - full
  - - debiased_estimation_loss
    - false
  - - train_data_dir
    - C:\Users\94427\kashiwa\Asuka\dataset
persistent_data_loader_workers:
  desc: null
  sort: 61
  value: false
pretrained_model_name_or_path:
  desc: null
  sort: 2
  value: runwayml/stable-diffusion-v1-5
print_only:
  desc: null
  sort: 1
  value:
    label: 'False'
prior_loss_weight:
  desc: null
  sort: 35
  value: 1.0
random_crop:
  desc: null
  sort: 63
  value: false
rank_dropout:
  desc: null
  sort: 115
  value: 0
rank_dropout_scale:
  desc: null
  sort: 82
  value: false
reg_data_dir:
  desc: null
  sort: 7
  value: ''
rescaled:
  desc: null
  sort: 84
  value: false
resume:
  desc: null
  sort: 34
  value: ''
sample_every_n_epochs:
  desc: null
  sort: 91
  value: 0
sample_every_n_steps:
  desc: null
  sort: 90
  value: 0
sample_prompts:
  desc: null
  sort: 93
  value: ''
sample_sampler:
  desc: null
  sort: 92
  value: euler_a
save_every_n_epochs:
  desc: null
  sort: 15
  value: 1
save_every_n_steps:
  desc: null
  sort: 107
  value: 0
save_last_n_steps:
  desc: null
  sort: 108
  value: 0
save_last_n_steps_state:
  desc: null
  sort: 109
  value: 0
save_model_as:
  desc: null
  sort: 31
  value: safetensors
save_precision:
  desc: null
  sort: 17
  value: fp16
save_state:
  desc: null
  sort: 33
  value: false
scale_v_pred_loss_like_noise_pred:
  desc: null
  sort: 112
  value: false
scale_weight_norms:
  desc: null
  sort: 113
  value: 0
sdxl:
  desc: null
  sort: 5
  value: false
sdxl_cache_text_encoder_outputs:
  desc: null
  sort: 117
  value: false
sdxl_no_half_vae:
  desc: null
  sort: 118
  value: true
seed:
  desc: null
  sort: 18
  value: ''
shuffle_caption:
  desc: null
  sort: 32
  value: false
stop_text_encoder_training_pct:
  desc: null
  sort: 27
  value: 0
text_encoder_lr:
  desc: null
  sort: 36
  value: 0.0001
train_batch_size:
  desc: null
  sort: 13
  value: 1
train_data_dir:
  desc: null
  sort: 126
  value: C:\Users\94427\kashiwa\Asuka\dataset
train_norm:
  desc: null
  sort: 85
  value: false
train_on_input:
  desc: null
  sort: 87
  value: true
training_comment:
  desc: null
  sort: 57
  value: ''
unet_lr:
  desc: null
  sort: 37
  value: 0.0001
unit:
  desc: null
  sort: 106
  value: 1
up_lr_weight:
  desc: null
  sort: 99
  value: ''
use_cp:
  desc: null
  sort: 79
  value: false
use_scalar:
  desc: null
  sort: 81
  value: false
use_tucker:
  desc: null
  sort: 80
  value: false
use_wandb:
  desc: null
  sort: 110
  value: false
v2:
  desc: null
  sort: 3
  value: false
v_parameterization:
  desc: null
  sort: 4
  value: false
v_pred_like_loss:
  desc: null
  sort: 65
  value: 0
vae:
  desc: null
  sort: 122
  value: ''
vae_batch_size:
  desc: null
  sort: 95
  value: 0
wandb_api_key:
  desc: null
  sort: 111
  value: ''
weighted_captions:
  desc: null
  sort: 105
  value: false
xformers:
  desc: null
  sort: 30
  value: xformers
